theme: jekyll-theme-minimal
title: /^chinarulez{,3}$/
logo: /assets/img/logo.jpg
description: Disassemble your life and find the key.

author:
  name: "Alexandr Savca"
  avatar: /assets/img/logo.jpg
  location: "In the middle of nowhere"
  links:
    - label: "Github"
      url: https://github.com/chinarulezzz
    - label: "Mail"
      url: mailto:alexandr.savca89@gmail.com

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: "single"
      author_profile: true

